


import java.util.Arrays;
 

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.SessionScoped;
 
@ManagedBean(name="user")
//@SessionScoped // The bean fields keep their values during a session

@RequestScoped // The bean fields keep their values during only one request. 
               //Either clicking the submit buttons, refreshing the page or loading the page again represent a new request.
public class UserBean{
 
	public String[] bookList;
	public String[] bookSelected;

    public void setBookSelected(String[] bookSelected) {
        this.bookSelected = bookSelected;
    }

    public String[] getBookSelected() {
        return bookSelected;
    }

		
	//Generated by Array
	public String[] getBookList() {
		
		bookList = new String[5];
		bookList[0] = "Book-1";
		bookList[1] = "Book-2";
		bookList[2] = "Book-3";
		bookList[3] = "Book-4";
		bookList[4] = "Book-5";
		
		return bookList;
	}
	
	public String bookSelectedInString() {
		return Arrays.toString(bookSelected);
	}
	
	
	
	
	
	
	
	
	
}